# Site settings
name: 光鱼 Blog
email: i@lightfish.cn
author: Lightfish Zhang
url: http://lightfish.cn
#resume_site: 
baseurl: ""
description: Stroms make trees take deeper roots.
meta_description: lightfish
motto: Stroms make trees take deeper roots.
banner: Stroms make trees take deeper roots.

github_username: lightfish-zhang
github: https://github.com/lightfish-zhang
stackoverflow: https://stackoverflow.com/users/7202973/lightfish

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : lightfish
    disqus :
        short_name : lightfish
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
