# Site settings
name: Lightfish Blog
email: i@lightfish.cn
author: Lightfish Zhang
url: http://www.lightfish.cc
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/lightfish-zhang/
baseurl: "/"
description: As a coder,listen keyborad
meta_description: lightfish
motto: It's our wits that make us men.
banner: As a coder,listen keyborad

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lightfish-zhang
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : disqus
    duoshuo:
        short_name : 
    disqus :
        short_name : lightfish
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
