# Site settings
name: 光魚 Blog
email: i@lightfish.cn
author: Lightfish Zhang
url: http://blog.lightfish.cn
#resume_site: 
baseurl: ""
description: If there is no light, I will light
meta_description: lightfish
motto: If there is no light, I will light - lightfish
banner: If there is no light, I will light

github_username: lightfish-zhang
github: https://github.com/lightfish-zhang
stackoverflow: https://stackoverflow.com/users/7202973/lightfish

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : disqus
    disqus :
        short_name : lightfish
#    duoshuo:
#        short_name : lightfish
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
