# Site settings
name: Lightfish Blog
email: i@lightfish.cn
author: Lightfish Zhang
url: http://www.lightfish.cc
#resume_site: 
github: https://github.com/lightfish-zhang/
baseurl: ""
description: As a coder, listen to keyboard
meta_description: lightfish
motto: Stroms make trees take deeper roots.
banner: As a coder, listen to keyboard

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lightfish-zhang
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : disqus
    duoshuo:
        short_name : lightfish
    disqus :
        short_name : lightfish
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
